### GET /api/users
GET http://localhost:3001/api/users

### POST /api/users fail
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "email": "bi7777777777777dul@jftyjftj.ki",
    "password": "",
    "name": "dthdrtjdrtjdrtjdtjdjdt"
}

### POST /api/users
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "email": "test@post19.api",
    "password": "mdppostapi19",
    "name": "jesuisle19eme"
}

### PUT /api/users
PUT http://localhost:3001/api/users/19
Content-Type: application/json

{
    "email": "blablabla@use10.ex",
    "password": "83hruuuturu7373",
    "name": "suisjevraiment le 19eme ?"
}
